version: '3.8'

services:
  # MongoDB database for users
  users_db:
    image: mongo:8.0
    container_name: users_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: users123
      MONGO_INITDB_DATABASE: users_db
    volumes:
      - users_mongodb_data:/data/db
    networks:
      - payments_network

  # MongoDB database for payments
  payments_db:
    image: mongo:8.0
    container_name: payments_mongodb
    restart: unless-stopped
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: payments123
      MONGO_INITDB_DATABASE: payments_db
    volumes:
      - payments_mongodb_data:/data/db
    networks:
      - payments_network

volumes:
  users_mongodb_data:
    driver: local
  payments_mongodb_data:
    driver: local

networks:
  payments_network:
    driver: bridge
